<?php

/**
 * Implements hook_views_api().
 */
function epe_dbimage_views_api() {
  return array("api" => "3.0");
}

/**
  * Implements hook_menu
  */
function epe_dbimage_menu() {
  $items = array();

  $items['api/resource/image'] = array(
    'title' => t('Restful Images Resource Query'),
    'page callback' => 'epe_dbimage_restful_api',
    'file' => 'epe_dbimage.rest.api.inc',
    'file path' => drupal_get_path('module', 'epe_dbimage') . '/inc',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['api/resource/image/%'] = array(
    'title' => t('Restful Single Image Resource Query'),
    'page callback' => 'epe_dbimage_restful_api_node',
    'page arguments' => array(3),
    'file' => 'epe_dbimage.rest.api.inc',
    'file path' => drupal_get_path('module', 'epe_dbimage') . '/inc',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_node_info().
 */
function epe_dbimage_node_info() {
  $items = array(
    'image_resource' => array(
      'name' => t('Image resource'),
      'base' => 'node_content',
      'description' => t('Use <em>Image resource</em> when creating image file resource'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}

/**
 * Implements hook_node_type_insert().
 */
function epe_dbimage_node_type_insert($content_type) {
  if ($content_type->type == 'image_resource') {
    module_load_include('inc','epe_dbimage','inc/epe_dbimage.field_base');
    module_load_include('inc','epe_dbimage','inc/epe_dbimage.field_instance');

    // Create all the fields we are adding to our content type.
    foreach (_image_resource_installed_fields() as $field) {
      //in case content type share fields
      if(!field_info_field($field['field_name'])) {
        field_create_field($field);
      }
    }

    // Create all the instances for our fields.
    foreach (_image_resource_installed_instances() as $instance) {
      field_create_instance($instance);
    }
    //assign custom content type permission
    _assign_epe_dbimage_permission();
  }
}

/*
 * assign custom content type permission base on epe supported author roles
 * the epe supported author roles is added from epe_wp module
 */
function _assign_epe_dbimage_permission() {
  foreach(variable_get('EPE_SUPPORTED_AUTHOR_ROLES',array()) as $role_name) {
    $role = user_role_load_by_name($role_name);
    $role_perm = user_role_permissions(array($role->rid=>$role_name)); //get permission for role
    $author_permissions = array(
      'epe dbfiles interface' => array('grant' => TRUE, 'module' => 'epe_dbfiles'),
      'create image_resource content' => array('grant' => TRUE, 'module' => 'node'),
      'delete any image_resource content' => array('grant' => FALSE, 'module' => 'node'),
      'delete own image_resource content' => array('grant' => TRUE, 'module' => 'node'),
      'edit any image_resource content' => array('grant' => FALSE, 'module' => 'node'),
      'edit own image_resource content' => array('grant' => TRUE, 'module' => 'node'),
    );
    //I am not sure what hook I should use to invoke user_role_grant_permissions function
    //with the current implementation, hook_node_type_insert has not create the associated permission at this stage
    foreach($author_permissions as $key=>$assignment) {
      if($assignment['grant'] && !array_key_exists($key, $role_perm[$role->rid])) {
        db_insert('role_permission')
          ->fields(array(
            'rid' => $role->rid,
            'permission' => $key,
            'module' => $assignment['module'],
          ))
          ->execute();
      }
    }
  }

  // Clear the user access cache.
  drupal_static_reset('user_access');
  drupal_static_reset('user_role_permissions');
}

/**
 * Implements hook_block_view_alter()
 * Provide default styling to views block
 * (******NOT USED NOW******)
 */
/*
function epe_dbimage_block_view_alter(&$data, $block) {
  $views_block_hashes = variable_get('views_block_hashes',array());
  foreach($views_block_hashes as $hash=>$value) {
    if($value == 'image_resource_index-block_list' && $block->delta == $hash) {
      drupal_add_css(drupal_get_path('module','epe_dbimage') . '/epe_dbimage.css');
    }
  }
}
*/

/**
 * Implements hook_default_search_api_index().
 */
function epe_dbimage_default_search_api_index() {
  $items = array();
  $items['image_resource_index'] = entity_create('search_api_index', array(
    'name' => 'image resource index',
    'machine_name' => 'image_resource_index',
    'description' => null,
    'server' => 'database_service',
    'item_type' => 'node',
    'options' => array(
      'index_directly' => 1,
      'cron_limit' => '50',
      'fields' => array(
        'nid' => array('type'=>'integer'),
        'type' => array('type'=>'string'),
        'title' => array('type'=>'text'),
        'url' => array('type'=>'string'),
        'status' => array('type'=>'integer'),
        'promote' => array('type'=>'boolean'),
        'created' => array('type'=>'date'),
        'changed' => array('type'=>'date'),
        'author' => array('type'=>'integer', 'entity_type'=>'user'),
        /*'field_public_status' => array('type'=>'string'),
        'field_featured_status' => array('type'=>'string'),*/
        'search_api_language' => array('type'=>'string'),
        'author:uid' => array('type'=>'integer'),
        'author:name' => array('type'=>'string'),
        'author:mail' => array('type'=>'string'),
        'author:field_account_fname' => array('type'=>'text'),
        'author:field_account_lname' => array('type'=>'text'),
        'body:value' => array('type'=>'text'),
      ),
      'data_alter_callbacks' => array(
        'search_api_alter_bundle_filter' => array(
          'status' => 1,
          'weight' => '-10',
          'settings' => array(
            'default' => 0,
            'bundles' => array('image_resource'=>'image_resource'),
          ),
          'search_api_alter_node_access' => array('status'=>0, 'weight'=>'0', 'settings'=>array()),
          'search_api_alter_node_status' => array('status'=>0, 'weight'=>'0', 'settings'=>array()),
          'search_api_alter_add_hierarchy' => array('status'=>0, 'weight'=>'0', 'settings'=>array('fields'=>array())),
          'search_api_alter_add_viewed_entity' => array('status'=>0, 'weight'=>'0', 'settings'=>array('mode'=>'full')),
          'search_api_alter_add_url' => array('status'=>0, 'weight'=>0, 'settings'=>array()),
          'search_api_alter_add_aggregation' => array('status'=>0, 'weight'=>0, 'settings'=>array()),
        ),
        'processors' => array(
          'search_api_case_ignore' => array('status'=>0, 'weight'=>0, 'settings'=>array('fields'=>array('title'=>true, 'body:value'=>true))),
          'search_api_html_filter' => array('status'=>0, 'weight'=>'10',
            'settings'=>array(
              'fields'=>array('title'=>true, 'body:value'=>true),
              'title'=>0, 'alt'=>1, 'tags'=>array('h1 = 5\\r\\nh2 = 3\\r\\nh3 = 2\\r\\nstrong = 2\\r\\nb = 2\\r\\nem = 1.5\\r\\nu = 1.5'),
            ),
          ),
          'search_api_tokenizer' => array('status'=>0, 'weight'=>'20',
            'fields'=>array('title'=>true, 'body:value'=>true),
            'spaces'=>'[^[:alnum:]]','ignorable'=>'[\\u0027]',
          ),
          'search_api_stopwords' => array('status'=>0, 'weight'=>'30', 'fields'=>array('title'=>true, 'body:value'=>true),'file'=>'','stopwords'=>'but\\r\\ndid\\r\\nthe this that those\\r\\netc',
          )
        ),
      ),
    ),
    'enabled' => '1',
    'read_only' => '0',
    'rdf_mapping' => array(),
  ));
  return $items;
}

/*
 * custom function for creating test node
 * this function may be removed in the future pending design
 * (******NOT USED NOW******)
 */
/*
function epe_dbimage_default_nodes() {
  global $user;
  //default node for image resource list block layout
  $node_values = array(
    'type' => 'page',
    'uid' => $user->uid,
    'status' => 1
  );
  $entity = entity_create('node', $node_values);
  $wrapper = entity_metadata_wrapper('node', $entity);
  $wrapper->title->set('image resource list');
  //$wrapper->url = 'image-resource-list';
  $wrapper->save(true);

  ctools_include('export');
  $context = ctools_export_new_object('context');
  $context->name = 'image-resource-list';
  $context->description = 'default image resource list page';
  $context->tag = 'block layout';
  $context->conditions = array(
    'path' => array(
      'values' => array(
        'image-resource-list' => 'image-resource-list',
      ),
    ),
  );
  $context->reactions = array(
    'block' => array(
      'blocks' => array(
        'views-4b5995069acedbe7bfa31e2745b013e6' => array(
          'module' => 'views',
          'delta' => '4b5995069acedbe7bfa31e2745b013e6',
          'region' => 'content',
          'weight' => '-10',
        ),
      ),
    ),
  );
  $context->condition_mode = 0;
  $saved = context_save($context);
}
*/
