<?php
/**
 * Implements hook_default_search_api_server().
 */
function epe_db_default_search_api_server() {
  $items = array();
  $items['database_service'] = entity_create('search_api_server', array(
    'name' => 'database-service',
    'machine_name' => 'database_service',
    'description' => '',
    'class' => 'search_api_db_service',
    'options' => array(
      'database' => 'default:default',
      'min_chars' => 3,
    ),
    'enabled' => 1,
  ));
  return $items;
}

/*
 * Implement hook_menu_local_tasks_alter()
 */
function epe_db_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if(arg(0) == 'node' && !arg(2)) {
    $node = node_load(arg(1));
    if($node && node_is_page($node)) {
      $depend_modules = variable_get('EPE_CONTENT_MODULES',array());
      foreach($depend_modules as $module=>$type) {
        if($type == 'file') {
          $file_type = str_replace('epe_db', '', $module);
          if($node->type === "{$file_type}_resource") {
            print_r($data['tabs'][0]['output'][1]);
            $data['tabs'][0]['output'][1]['#link']['path'] = 'resource/file/%/edit';
            $data['tabs'][0]['output'][1]['#link']['href'] = "resource/file/{$node->nid}/edit";
          }
        }
      }
    }
  }
}
