<?php

/**
 * Implements hook_views_api().
 */
function epe_dbimage_views_api() {
  return array("api" => "3.0");
}

/**
  * Implements hook_menu
  */
function epe_dbimage_menu() {
  $items = array();

  $items['api/resource/image'] = array(
    'title' => t('Restful Images Resource Query'),
    'page callback' => 'epe_dbimage_restful_api',
    'file' => 'epe_dbimage.rest.api.inc',
    'file path' => drupal_get_path('module', 'epe_dbimage') . '/inc',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['api/resource/image/%'] = array(
    'title' => t('Restful Single Image Resource Query'),
    'page callback' => 'epe_dbimage_restful_api_node',
    'page arguments' => array(3),
    'file' => 'epe_dbimage.rest.api.inc',
    'file path' => drupal_get_path('module', 'epe_dbimage') . '/inc',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_node_info().
 */
function epe_dbimage_node_info() {
  $items = array(
    'image_resource' => array(
      'name' => t('Image resource'),
      'base' => 'node_content',
      'description' => t('Use <em>Image resource</em> when creating image file resource'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}


/**
 * Implements hook_theme_registry_alter()
**/
function epe_dbimage_theme_registry_alter(&$theme_registry) {
  $template_path = drupal_get_path('module', 'epe_dbimage') . '/templates';
  $theme_registry_copy = $theme_registry;       // munge on a copy
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pow', $template_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('node');
  foreach ($hooks as $h) {
    _epe_dbimage_insert_after_first_element($theme_registry[$h]['theme paths'], $template_path);
  }
}

/**
 * Helper function for re-ordering arrays (needed by theme_registry_alter)
*/
function _epe_dbimage_insert_after_first_element(&$a, $element) {
  if(is_array($a)) {
    $first_element = array_shift($a);
    array_unshift($a, $first_element, $element);
  }
}

/**
 * Implements hook_node_type_insert().
 */
function epe_dbimage_node_type_insert($content_type) {
  if ($content_type->type == 'image_resource') {
    module_load_include('inc','epe_dbimage','inc/epe_dbimage.field_base');
    module_load_include('inc','epe_dbimage','inc/epe_dbimage.field_instance');

    // Create all the fields we are adding to our content type.
    foreach (_image_resource_installed_fields() as $field) {
      //in case content type share fields
      if(!field_info_field($field['field_name'])) {
        field_create_field($field);
      }
    }

    // Create all the instances for our fields.
    foreach (_image_resource_installed_instances() as $instance) {
      field_create_instance($instance);
    }
    //assign custom content type permission
    _assign_epe_dbimage_permission();
  }
}

function epe_dbimage_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'image_resource_node_form') {
    if(is_numeric(arg(1)) && arg(2) == 'edit') {
    $form['header'] = array(
      '#type'=>'container',
      '#prefix'=>'<div style="background-color: #c8d5de;padding:23px;margin-bottom:20px;"><div style="border: 1px solid #0195bd;background-color: #fff;padding:20px 31px;">',
      '#weight'=>-20,
    );

    $form['footer'] = array(
      '#type'=>'container',
      '#suffix'=>'</div></div>',
      '#weight'=>30,
    );
    }

    if(is_numeric(arg(1))) {
      $destination = 'node/' . arg(1);
    } else {
      $destination = 'db/';
    }

    $form['destination'] = array(
      '#type'=>'hidden',
      '#value'=>$destination,
    );

    $form['field_featured_status']['#type'] = 'hidden';
    $form['field_public_status']['#type'] = 'hidden';
    $form['field_image_resource_file']['#weight'] = -10;
    $form['field_image_resource_file']['und'][0]['#title'] = 'Image Resource File';

    $form['#attached']['css'] = array(
      drupal_get_path('module', 'epe_dbimage') . '/epe_dbimage_form.css',
    );

    if(is_numeric(arg(1))) {
      $form['actions']['saveas'] = array(
        '#type'=>'submit',
        '#access'=>1,
        '#value'=>t('Save As New'),
        '#weight'=>2,
        '#submit'=>array(
          'epe_dbimage_save_as_submit',
          'node_form_submit',
        ),
      );

      $form['actions']['cancel']['#submit'] = array('epe_dbimage_cancel_from_edit_handler');
    }
  }
}

function epe_dbimage_save_as_submit($form, &$form_state) {
  $form_state['node']->vid = '';
  $form_state['node']->nid = '';
  $form_state['node']->status = 0;
  $form_state['node']->created = '';
  $form_state['node']->changed = '';
  $form_state['node']->is_new = 1;
  $form_state['node']->date = '';
  $form_state['node']->field_featured_status = array(
    'und'=>array(
      0=>array(
        ['value'] => 'Not-Featured'
      )
    )
  );
  $form_state['node']->field_public_status = array(
    'und'=>array(
      0=>array(
        ['value'] => 'Private'
      )
    )
  );
  $form_state['values']['nid'] = '';
  $form_state['values']['vid'] = '';
}

function epe_dbimage_cancel_from_edit_handler($form, &$form_state) {
  $form_state['redirect'] = 'node/' . $form['nid']['#value'];
}


/*
 * assign custom content type permission base on epe supported author roles
 * the epe supported author roles is added from epe_wp module
 */
function _assign_epe_dbimage_permission() {
  foreach(variable_get('EPE_SUPPORTED_AUTHOR_ROLES',array()) as $role_name) {
    $role = user_role_load_by_name($role_name);
    $role_perm = user_role_permissions(array($role->rid=>$role_name)); //get permission for role
    $author_permissions = array(
      'epe dbfiles interface' => array('grant' => TRUE, 'module' => 'epe_dbfiles'),
      'create image_resource content' => array('grant' => TRUE, 'module' => 'node'),
      'delete any image_resource content' => array('grant' => FALSE, 'module' => 'node'),
      'delete own image_resource content' => array('grant' => TRUE, 'module' => 'node'),
      'edit any image_resource content' => array('grant' => FALSE, 'module' => 'node'),
      'edit own image_resource content' => array('grant' => TRUE, 'module' => 'node'),
    );
    //I am not sure what hook I should use to invoke user_role_grant_permissions function
    //with the current implementation, hook_node_type_insert has not create the associated permission at this stage
    foreach($author_permissions as $key=>$assignment) {
      if($assignment['grant'] && !array_key_exists($key, $role_perm[$role->rid])) {
        db_insert('role_permission')
          ->fields(array(
            'rid' => $role->rid,
            'permission' => $key,
            'module' => $assignment['module'],
          ))
          ->execute();
      }
    }
  }

  // Clear the user access cache.
  drupal_static_reset('user_access');
  drupal_static_reset('user_role_permissions');
}

/**
 * Implements hook_default_search_api_index().
 */
function epe_dbimage_default_search_api_index() {
  module_load_include('inc','epe_db','inc/epe_db.search_api_index_base_definition');
  $items = array();
  $items['image_resource_index'] = entity_import('search_api_index', _epe_db_search_api_index_base_definition('image resource search index','image_resource_index',array('image_resource')));
  return $items;
}
