<?php 

function epe_wp_epe_home() {
  return array(
    'my_content' => array(
      '#type' => 'markup',
      '#markup' => 'Placeholder for EPE home page',
    ),
  );
}

function epe_wp_ev_home() {
  return array(
    'my_content' => array(
      '#type' => 'markup',
      '#markup' => 'Placeholder for EV home page',
    ),
  );
}

function epe_wp_cm_home() {
  return array(
    'my_content' => array(
      '#type' => 'markup',
      '#markup' => 'Placeholder for CM home page',
    ),
  );
}

function epe_wp_llb_home() {
  return array(
    'my_content' => array(
      '#type' => 'markup',
      '#markup' => 'Placeholder for LLB home page',
    ),
  );
}

function epe_wp_db_home() {
  return array(
    'my_content' => array(
      '#type' => 'markup',
      '#markup' => 'Placeholder for Resources home page',
    ),
  );
}

