<?php
/**
 * Implements hook_views_api().
 */
function epe_db_views_api() {
  return array("api" => "3.0");
}

function epe_db_menu() {
  $items = array();

  $items['api/resource/lookup'] = array(
    'title' => t('Resource Lookup'),
    'page callback' => 'epe_db_node_lookup',
    'file' => 'epe_db.rest.api.inc',
    'file path' => drupal_get_path('module', 'epe_db') . '/inc',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['node/%node/deleteresource'] = array(
    'title' => t('Delete a resource'),
    'page callback' => 'epe_db_node_delete_function',
    'page arguments' => array(1),
    'file' => 'epe_db.pages.inc',
    'access callback' => 'epe_db_resource_can_do_delete',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );

  $items['node/%node/submitpublic'] = array(
    'title' => t('Submit a resource to public db'),
    'page callback' => 'epe_db_node_submit_public_function',
    'page arguments' => array(1),
    'file' => 'epe_db.pages.inc',
    'access callback' => 'epe_db_resource_can_do_submitpublic',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );

  $items['node/%node/unsubmitpublic'] = array(
    'title' => t('Unsubmit a resource to public db'),
    'page callback' => 'epe_db_node_unsubmit_public_function',
    'page arguments' => array(1),
    'file' => 'epe_db.pages.inc',
    'access callback' => 'epe_db_resource_can_do_unsubmit',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );

  $items['node/%node/approvepublic'] = array(
    'title' => t('Approve a resource to public db'),
    'page callback' => 'epe_db_node_approve_public_function',
    'page arguments' => array(1),
    'file' => 'epe_db.pages.inc',
    'access callback' => 'user_access',
    'access arguments' => array('epe dbpublic approve'),
    'type' => MENU_CALLBACK,
  );

  $items['node/%node/rejectpublic'] = array(
    'title' => t('Reject a resource to public db'),
    'page callback' => 'epe_db_node_reject_public_function',
    'page arguments' => array(1),
    'file' => 'epe_db.pages.inc',
    'access callback' => 'user_access',
    'access arguments' => array('epe dbpublic approve'),
    'type' => MENU_CALLBACK,
  );

  $items['node/%node/feature'] = array(
    'title' => t('Feature a resource'),
    'page callback' => 'epe_db_node_feature_function',
    'page arguments' => array(1),
    'file' => 'epe_db.pages.inc',
    'access callback' => 'user_access',
    'access arguments' => array('epe dbpublic feature'),
    'type' => MENU_CALLBACK,
  );

  $items['node/%node/unfeature'] = array(
    'title' => t('Unfeature a resource'),
    'page callback' => 'epe_db_node_unfeature_function',
    'page arguments' => array(1),
    'file' => 'epe_db.pages.inc',
    'access callback' => 'user_access',
    'access arguments' => array('epe dbpublic unfeature'),
    'type' => MENU_CALLBACK,
  );

  $items['node/%node/share'] = array(
    'title' => t('Share a resource'),
    'page callback' => 'epe_db_node_share_function',
    'page arguments' => array(1),
    'file' => 'epe_db.pages.inc',
    'access callback' => 'epe_db_resource_can_do_share',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );

  $items['node/%node/unshare'] = array(
    'title' => t('Unshare a resource'),
    'page callback' => 'epe_db_node_unshare_function',
    'page arguments' => array(1),
    'file' => 'epe_db.pages.inc',
    'access callback' => 'epe_db_resource_can_do_unshare',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );


  return $items;
}

function epe_db_node_view_alter(&$build) {
  $epe_help = variable_get('epe_help',array('path'=>array()));
  $nodeurl = drupal_get_path_alias("node/{$build['#node']->nid}");
  if($build['#view_mode'] == 'full' && $build['#entity_type'] == 'node' && $build['#bundle'] == 'page') {
    foreach($epe_help['path'] as $key => $id) {
      if($build['#node']->nid == $id) {
        unset($build['field_tags']);
        unset($build['links']);
        $build['post_render_param'] = $key;
        $build['#post_render'][] = 'epe_db_help_content_render';
      }
    }
    //remove tag & link from individual kb page
    $nodeurlarray = explode('/',$nodeurl);
    if($nodeurlarray[0] == 'help') {
      if(isset($build['field_tags'])) unset($build['field_tags']);
      if(isset($build['links'])) unset($build['links']);
    }
  }
  if(isset($build['links']['statistics'])) unset($build['links']['statistics']);
}

function epe_db_node_view($node, $view_mode) {
  if($node->type == 'page' && $view_mode == 'full') {
    $nodeurl = drupal_get_path_alias("node/{$node->nid}");
    //this should only apply to section & individual kb page, skip main index page
    $nodeurlarray = explode('/',$nodeurl);
    if($nodeurlarray[0] == 'help' && count($nodeurlarray) > 1) {
      $node->content['breadcrumb'] = array(
        '#type' => 'item',
        '#weight' => -11,
        '#markup' => '<div class="epe_help">' . epe_wp_render_block_content('epe_db', 'epe_kb_breadcrumb') . '</div>'
      );

      $node->content['subtitle'] = array(
        '#type' => 'item',
        '#weight' => -10,
        '#markup' => '<div class="epe_help subtitle">' . $node->title . '</div>'
      );

      $node->title = 'EPE Knowledge Base';
      drupal_set_title($node->title);
    }
  }
  return $node;
}

/*
 * Implement hook_theme
 * This hook is to style edit form, the theme key needs to be the same as the form function name
 */
function epe_db_theme() {
  $tpl_path = drupal_get_path('module','epe_db') . '/templates';
  return array(
    'epe_help_index_content' => array(
      'path' => $tpl_path,
      'template' => 'epe_help_index',
      'variables' => array(
        'content' => array(),
        'tag' => array(),
      ),
    ),
    'epe_help_section_content' => array(
      'path' => $tpl_path,
      'template' => 'epe_help_section',
      'variables' => array(
        'tag' => array(),
      ),
    ),
  );
}

function epe_db_help_content_render($content, $element) {
  $theme_key = 'epe_help_index_content';
  if($element['post_render_param'] != 'kb') $theme_key = 'epe_help_section_content';
  return theme($theme_key,array('content'=>$content,'tag'=>array($element['post_render_param'])));
}

/**
 * Implements hook_default_search_api_server().
 */
function epe_db_default_search_api_server() {
  $items = array();
  $items['database_service'] = entity_create('search_api_server', array(
    'name' => 'database-service',
    'machine_name' => 'database_service',
    'description' => '',
    'class' => 'search_api_db_service',
    'options' => array(
      'database' => 'default:default',
      'min_chars' => 3,
    ),
    'enabled' => 1,
  ));
  return $items;
}

function epe_db_default_search_api_index() {
  $items = array();
  $items['published_basic_page_index'] = entity_import('search_api_index', '{
    "name" : "published basic page index",
    "machine_name" : "published_basic_page_index",
    "description" : null,
    "server" : "database_service",
    "item_type" : "node",
    "options" : {
      "index_directly" : 1,
      "cron_limit" : "50",
      "fields" : {
        "nid" : { "type" : "integer" },
        "title" : { "type" : "text" },
        "url" : { "type" : "uri" },
        "created" : { "type" : "date" },
        "changed" : { "type" : "date" },
        "field_tags" : { "type" : "list\\u003Cinteger\\u003E", "entity_type" : "taxonomy_term" },
        "search_api_language" : { "type" : "string" },
        "body:value" : { "type" : "text" }
      },
      "data_alter_callbacks" : {
        "search_api_alter_bundle_filter" : {
          "status" : 1,
          "weight" : "-10",
          "settings" : { "default" : "0", "bundles" : { "page" : "page" } }
        },
        "search_api_alter_node_access" : { "status" : 0, "weight" : "0", "settings" : [] },
        "search_api_alter_node_status" : { "status" : 1, "weight" : "0", "settings" : [] },
        "search_api_alter_add_hierarchy" : { "status" : 0, "weight" : "0", "settings" : { "fields" : [] } },
        "search_api_alter_add_viewed_entity" : { "status" : 0, "weight" : "0", "settings" : { "mode" : "full" } },
        "search_api_alter_add_url" : { "status" : 0, "weight" : "0", "settings" : [] },
        "search_api_alter_add_aggregation" : { "status" : 0, "weight" : "0", "settings" : [] }
      },
      "processors" : {
        "search_api_case_ignore" : {
          "status" : 1,
          "weight" : "0",
          "settings" : { "fields" : { "title" : true, "body:value" : true } }
        },
        "search_api_html_filter" : {
          "status" : 1,
          "weight" : "10",
          "settings" : {
            "fields" : { "title" : true, "body:value" : true },
            "title" : 0,
            "alt" : 1,
            "tags" : "h1 = 5\\r\\nh2 = 3\\r\\nh3 = 2\\r\\nstrong = 2\\r\\nb = 2\\r\\nem = 1.5\\r\\nu = 1.5"
          }
        },
        "search_api_tokenizer" : {
          "status" : 0,
          "weight" : "20",
          "settings" : {
            "fields" : { "title" : true, "body:value" : true },
            "spaces" : "[^[:alnum:]]",
            "ignorable" : "[\\u0027]"
          }
        },
        "search_api_stopwords" : {
          "status" : 0,
          "weight" : "30",
          "settings" : {
            "fields" : { "title" : true, "body:value" : true },
            "file" : "",
            "stopwords" : "but\\r\\ndid\\r\\nthe this that those\\r\\netc"
          }
        }
      }
    },
    "enabled" : "1",
    "read_only" : "0",
    "rdf_mapping" : []
  }');
  return $items;
}

/*
 * Implement hook_menu_local_tasks_alter()
 */
/*function epe_db_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if(arg(0) == 'node' && !arg(2)) {
    $node = node_load(arg(1));
    if($node && node_is_page($node)) {
      $depend_modules = variable_get('EPE_CONTENT_MODULES',array());
      foreach($depend_modules as $module=>$type) {
        if($type == 'file') {
          $file_type = str_replace('epe_db', '', $module);
          if($node->type === "{$file_type}_resource") {
            $data['tabs'][0]['output'][1]['#link']['path'] = 'resource/file/%/edit';
            $data['tabs'][0]['output'][1]['#link']['href'] = "resource/file/{$node->nid}/edit";
          }
        }
      }
    }
  }
}*/


/*
 * Alter the cancel behavior of the edit forms
 */
function epe_db_form_alter (&$form, &$form_state, $form_id) {
  if ($form['#id'] == 'cm-resource-node-form' || $form['#id'] == 'image-resource-node-form' || $form['#id'] == 'audio-resource-node-form' || $form['#id'] == 'video-resource-node-form' || $form['#id'] == 'document-resource-node-form' || $form['#id'] == 'llb-resource-node-form' || $form['#id'] == 'ev-tool-instance-node-form') {
  $form['actions']['cancel'] = array(
      '#type'   => 'submit',
      '#value'  => t('Cancel'),
      '#submit' => array('callback_for_cancel_button'),
      '#limit_validation_errors' => array(),
      '#weight'  => 99,
    );
    $form['actions']['delete']['#access'] = FALSE;
    $form['actions']['preview']['#access'] = FALSE;
  }
}
function callback_for_cancel_button($form, &$form_state) {
  $url = '';
  if(isset($_POST['destination'])) {
    $_POST['destination'] ? $_POST['destination'] : '';
  }
  drupal_goto($url);
}


/**
  * setup the approve and feature permissions
  */
function epe_db_permission() {
  return array(
    'epe dbpublic approve' => array(
      'title' => 'EPE DB Public Approval',
      'description' => 'Allow user to approve items for inclusion in the public db.',
    ),
    'epe dbpublic feature' => array(
      'title' => 'EPE DB Feature Resources',
      'description' => 'Allow user to feature resources.',
    ),
  );
}

/**
 * Implements hook_bean_types_api_info().
 */
function epe_db_bean_types_api_info() {
  return array('api' => 4);
}

/**
 * Implements hook_bean_types().
 */
function epe_db_bean_types() {
  $plugins = array();
  $plugins['content_rotator'] = array(
    'label' => t('Content Rotator'),
    'description' => t('Use this &lt;em&gt;Content Rotator&lt;/em&gt; to create an embeddable carousel block'),
  );
  return $plugins;
}


/**
 * Implements hook_theme_registry_alter()
**/
function epe_db_theme_registry_alter(&$theme_registry) {
  $template_path = drupal_get_path('module', 'epe_db') . '/templates';
  $theme_registry_copy = $theme_registry;       // munge on a copy
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pow', $template_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('bean');
  foreach ($hooks as $h) {
    _epe_db_insert_after_first_element($theme_registry[$h]['theme paths'], $template_path);
  }
}

/**
 * Helper function for re-ordering arrays (needed by theme_registry_alter)
*/
function _epe_db_insert_after_first_element(&$a, $element) {
  if(is_array($a)) {
    $first_element = array_shift($a);
    array_unshift($a, $first_element, $element);
  }
}

function epe_db_resource_can_do_submitpublic($node) {
  global $user;
  return ($node->uid == $user->uid || in_array('administrator', $user->roles));
}

function epe_db_resource_can_do_delete($node) {
  global $user;
  return ($node->uid == $user->uid || in_array('administrator', $user->roles));
}

function epe_db_resource_can_do_unsubmit($node) {
  global $user;
  return ($node->uid == $user->uid || in_array('administrator', $user->roles));
}

function epe_db_resource_can_do_share($node) {
  global $user;
  return ($node->uid == $user->uid || in_array('administrator', $user->roles));
}

function epe_db_resource_can_do_unshare($node) {
  global $user;
  return ($node->uid == $user->uid || in_array('administrator', $user->roles));
}

function epe_db_block_info()  {
  $blocks = array();

  $blocks['epe_kb_breadcrumb'] = array(
    'info' => t('EPE Knowledge Base Breadcrumb'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

function epe_db_block_view($delta='') {
  $block = array();

  switch($delta) {
    case 'epe_kb_breadcrumb':
      $epe_help = variable_get('epe_help',array('path'=>array()));
      $node = node_load(arg(1));
      $nodeurl = drupal_get_path_alias('node/' . arg(1));
      $nodeurlarray = explode('/',$nodeurl);
      $breadcrumb = '<div class="breadcrumb">' . l('EPE Knowledge Base',$nodeurlarray[0]);
      if(count($nodeurlarray) > 2) {
        $alias = "{$nodeurlarray[0]}/{$nodeurlarray[1]}";
        $path = drupal_lookup_path("source", $alias);
        $bc_node = menu_get_object("node", 1, $path);
        $breadcrumb .= " >> " . l($bc_node->title, $alias);
      }
      $breadcrumb .= " >> " . $node->title;
      $breadcrumb .= '</div>';

      $block['title'] = '';
      $block['content'] = $breadcrumb;
    break;
  }

  return $block;
}
