<?php
/**
 * Implements hook_views_api().
 */
function epe_dbmultimedia_views_api() {
  return array("api" => "3.0");
}

/*
 * Implements hook_menu
 */
function epe_dbmultimedia_menu() {
  $items = array();

  $items['api/resource/multimedia'] = array(
    'title' => t('Restful Multimedia Resource Query'),
    'page callback' => 'epe_dbmultimedia_restful_api',
    'file' => 'epe_dbmultimedia.rest.api.inc',
    'file path' => drupal_get_path('module', 'epe_dbmultimedia') . '/inc',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['api/resource/multimedia/%'] = array(
    'title' => t('Restful Single Multimedia Resource Query'),
    'page callback' => 'epe_dbmultimedia_restful_api_node',
    'page arguments' => array(3),
    'file' => 'epe_dbmultimedia.rest.api.inc',
    'file path' => drupal_get_path('module', 'epe_dbmultimedia') . '/inc',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_default_search_api_index().
 */
function epe_dbmultimedia_default_search_api_index() {
  module_load_include('inc','epe_db','inc/epe_db.search_api_index_base_definition');
  $items = array();
  $items['multimedia_resource_index'] = entity_import('search_api_index', _epe_db_search_api_index_base_definition('multimedia resource search index','multimedia_resource_index',array('audio_resource','video_resource','web_resource'),array(array('field'=>'field_resource_url:url','type'=>'string'),array('field'=>'field_resource_origin','type'=>'string'))));
  return $items;
}
