<?php
/**
 * Implements hook_views_api().
 */
function epe_dbmultimedia_views_api() {
  return array("api" => "3.0");
}

/*
 * Implements hook_menu
 */
function epe_dbmultimedia_menu() {
  $items = array();

  $items['api/resource/multimedia'] = array(
    'title' => t('Restful Multimedia Resource Query'),
    'page callback' => 'epe_dbmultimedia_restful_api',
    'file' => 'epe_dbmultimedia.rest.api.inc',
    'file path' => drupal_get_path('module', 'epe_dbmultimedia') . '/inc',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['api/resource/multimedia/%'] = array(
    'title' => t('Restful Single Multimedia Resource Query'),
    'page callback' => 'epe_dbmultimedia_restful_api_node',
    'page arguments' => array(3),
    'file' => 'epe_dbmultimedia.rest.api.inc',
    'file path' => drupal_get_path('module', 'epe_dbmultimedia') . '/inc',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_default_search_api_index().
 */
function epe_dbmultimedia_default_search_api_index() {
  $items = array();
  $items['multimedia_resource_index'] = entity_create('search_api_index', array(
    'name' => 'multimedia_resource_index',
    'machine_name' => 'multimedia_resource_index',
    'description' => null,
    'server' => 'database_service',
    'item_type' => 'node',
    'options' => array(
      'index_directly' => 1,
      'cron_limit' => '50',
      'fields' => array(
        'nid' => array('type'=>'integer'),
        'type' => array('type'=>'string'),
        'title' => array('type'=>'text'),
        'url' => array('type'=>'string'),
        'edit_url' => array('type'=>'uri'),
        'status' => array('type'=>'integer'),
        'promote' => array('type'=>'boolean'),
        'created' => array('type'=>'date'),
        'changed' => array('type'=>'date'),
        'author' => array('type'=>'integer', 'entity_type'=>'user'),
        'search_api_language' => array('type'=>'string'),
        'author:uid' => array('type'=>'integer'),
        'author:name' => array('type'=>'string'),
        'author:mail' => array('type'=>'string'),
        'author:field_account_fname' => array('type'=>'text'),
        'author:field_account_lname' => array('type'=>'text'),
        'author:field_account_organization' => array('type'=>'text'),
        'body:value' => array('type'=>'text'),
        'body:summary' => array('type'=>'text'),
      ),
      'data_alter_callbacks' => array(
        'search_api_alter_bundle_filter' => array(
          'status' => 1,
          'weight' => '-10',
          'settings' => array(
            'default' => 0,
            'bundles' => array('audio_resource'=>'audio_resource', 'video_resource'=>'video_resource'),
          ),
          'search_api_alter_node_access' => array('status'=>0, 'weight'=>'0', 'settings'=>array()),
          'search_api_alter_node_status' => array('status'=>0, 'weight'=>'0', 'settings'=>array()),
          'search_api_alter_add_hierarchy' => array('status'=>0, 'weight'=>'0', 'settings'=>array('fields'=>array())),
          'search_api_alter_add_viewed_entity' => array('status'=>0, 'weight'=>'0', 'settings'=>array('mode'=>'full')),
          'search_api_alter_add_url' => array('status'=>0, 'weight'=>0, 'settings'=>array()),
          'search_api_alter_add_aggregation' => array('status'=>1,'weight'=>0,'settings'=>array(
                'fields'=>array('search_api_aggregation_1'=>array(
                  'name'=>'title_main_body_fulltext_search',
                  'type'=>'fulltext',
                  'fields'=>array('title','body:value'),
                  'description'=>'A Fulltext aggregation of the following fields: Title, The main body text \\u00bb Text.',
                ),
              ),
            ),
          ),
        ),
        'processors' => array(
          'search_api_case_ignore' => array('status'=>0, 'weight'=>0, 'settings'=>array('fields'=>array('title'=>true, 'body:value'=>true, 'author:field_account_fname'=>true,
              'author:field_account_lname' => true))),
          'search_api_html_filter' => array('status'=>0, 'weight'=>'10',
            'settings'=>array(
              'fields'=>array('title'=>true, 'body:value'=>true),
              'title'=>0, 'alt'=>1, 'tags'=>array('h1 = 5\\r\\nh2 = 3\\r\\nh3 = 2\\r\\nstrong = 2\\r\\nb = 2\\r\\nem = 1.5\\r\\nu = 1.5'),
            ),
          ),
          'search_api_tokenizer' => array('status'=>0, 'weight'=>'20',
            'fields'=>array('title'=>true, 'body:value'=>true),
            'spaces'=>'[^[:alnum:]]','ignorable'=>'[\\u0027]',
          ),
          'search_api_stopwords' => array('status'=>0, 'weight'=>'30', 'fields'=>array('title'=>true, 'body:value'=>true),'file'=>'','stopwords'=>'but\\r\\ndid\\r\\nthe this that those\\r\\netc',
          )
        ),
      ),
    ),
    'enabled' => '1',
    'read_only' => '0',
    'rdf_mapping' => array(),
  ));
  return $items;
}
