<?php
/**
  * Implement hook_menu
  */
function epe_dbresource_browser_menu() {
  $items = array();

  $items['resource-browser'] = array(
    'title' => t('Resource Browser'),
    'page callback' => 'epe_dbresource_browser_index',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['dialog/resource-browser'] = array(
    'title' => t('Resource Browser'),
    'page callback' => 'epe_dbresource_browser_dialog_index',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['api/resource/pager'] = array(
    'title' => t('Restful Resource Pager Query'),
    'page callback' => 'epe_dbresource_browser_pager_api',
    'file' => 'epe_dbresource_browser.rest.api.inc',
    'file path' => drupal_get_path('module', 'epe_dbresource_browser') . '/inc',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function epe_dbresource_browser_theme() {
  $path = drupal_get_path( 'module' , 'epe_dbresource_browser' ) . '/app';
  return array(
    'rb_main'=>array(
      'path'=>"$path",
      'template'=>'rb.main', //main index file
    ),
  );
}

function epe_dbresource_browser_dialog_index() {
  module_invoke('admin_menu', 'suppress');
  drupal_add_js(libraries_get_path('underscore') . '/underscore-min.js');

  epe_dbresource_browser_preload();

  drupal_add_js('(function($){$(function() {Drupal.settings.resourceBrowser.editmode=true;})})(jQuery);','inline');

  return theme('rb_main');
}

function epe_dbresource_browser_index() {
  epe_dbresource_browser_preload();
  return theme('rb_main');
}

function epe_dbresource_browser_preload() {
  global $user;
  //setup filter
  $resource_filter = array(
    array('filter'=>'','label'=>'All Resources'),
  );
  //add filter if not anonymous user
  if($user->uid > 0) {
    $resource_filter[] = array('filter'=>'author','label'=>'My Resources');
    $resource_filter[] = array('filter'=>'favorited','label'=>'My Favorited Resources');
  }

  $resource_filter[] = array('filter'=>'featured','label'=>'Featured Resources');

  $epe_modules = variable_get('EPE_CONTENT_MODULES',array());
  $resource_browser_enabled_modules = array();
  foreach($epe_modules as $module) {
    if(isset($module['resource_browser'])) {
      $enabled_module = array();
      if(isset($module['resource_browser']['label'])) {
        $enabled_module['label'] = $module['resource_browser']['label'];
      } else {
        $node_type = node_type_load(str_replace('_','-',$module['content_type']));
        $enabled_module['label'] = $node_type->name;
      }

      $enabled_module['api'] = $module['resource_browser']['api'];
      if(isset($module['resource_browser']['default'])) {
        $enabled_module['default'] = $module['resource_browser']['default'];
      }
      if(isset($module['resource_browser']['weight'])) {
        $enabled_module['weight'] = $module['resource_browser']['weight'];
      }
      if(isset($module['resource_browser']['adurl'])) {
        $enabled_module['adurl'] = base_path() . $module['resource_browser']['adurl'];
      }
      $enabled_module['adimagepath'] = base_path() . drupal_get_path('module','epe_dbresource_browser') . '/images/rb-ads-' . $enabled_module['api'] . '.jpg';
      $enabled_module['page'] = 1;
      $enabled_module['sort'] = 'title';

      $resource_browser_enabled_modules[] = $enabled_module;
    }
  }
  usort($resource_browser_enabled_modules,"_epe_dbresource_browser_module_sort");

  drupal_add_js(array('jslibraries'=>array(
    'path'=>array(
      'angular'=>base_path() . libraries_get_path('angular-1.2.18'),
      'requirejs'=>base_path() . libraries_get_path('requirejs'),
      'angularAMD'=>base_path() . libraries_get_path('angularAMD'),
      'ngProgress'=>base_path() . libraries_get_path('ngProgress'),
      'angularPaging'=>base_path() . libraries_get_path('angular-paging'),
      'angularUi'=>base_path() . libraries_get_path('angular-ui-bootstrap'),
      'angularWebstorage'=>base_path() . libraries_get_path('angular-webstorage'),
      'loadingBar'=>base_path() . libraries_get_path('angular-loading-bar'),
    ),
  )),'setting');
  drupal_add_js(array('resourceBrowser'=>array(
    'appPath'=>base_path() . drupal_get_path('module','epe_dbresource_browser') . '/app',
    'resource_filter'=>json_encode($resource_filter),
    'epe_modules'=>json_encode($resource_browser_enabled_modules),
    'page_size'=>10,
    'editmode'=>false,
  )),'setting');
  drupal_add_js(array('user'=>array(
    'is_logged_in'=>user_is_logged_in(),
    'username'=>$user->name,
  )),'setting');


  drupal_add_css('http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css','external');
  drupal_add_css(drupal_get_path('module','epe_dbresource_browser') . '/css/epe_resource_browser.css');
  drupal_add_css(drupal_get_path('module','epe_dbresource_browser') . '/css/bootstrap3_glyphicons/css/bootstrap.min.css');
  drupal_add_css(libraries_get_path('ngProgress') . '/ngProgress.css');
}

/**
 * custom sort function to sort module order by weight
 */
function _epe_dbresource_browser_module_sort($mod_a, $mod_b) {
  return $mod_a['weight'] > $mod_b['weight'];
}

function epe_dbresource_browser_page_alter(&$page) {
  if (isset($page['content']['system_main']['#block']->theme)) {
    if ($page['content']['system_main']['#block']->theme == 'blank') {
      if (isset($page['page_top']['toolbar']['#access'])) {
        $page['page_top']['toolbar']['#access'] = 0;
      }
    }
  }
}

/**
 * Implements hook_image_default_styles().
 */
function epe_dbresource_browser_image_default_styles() {
  $styles = array();

  $styles['resource_browser_thumbnail'] = array(
    'name' => 'resource_browser_thumbnail',
    'effects' => array(
      4 => array(
        'label' => 'Scale and crop',
        'help' => 'Scale and crop will maintain the aspect-ratio of the original image, then crop the larger dimension. This is most useful for creating perfectly square thumbnails without stretching the image.',
        'effect callback' => 'image_scale_and_crop_effect',
        'dimensions callback' => 'image_resize_dimensions',
        'form callback' => 'image_resize_form',
        'summary theme' => 'image_resize_summary',
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 133,
          'height' => 99,
        ),
        'weight' => 1,
      ),
    ),
  );

  return $styles;
}

/*
 * Following are not working, why?? they are better then adding drupal_add_js, need to figure out why
 */
/*
function epe_dbresource_browser_library_alter(&$libraries, $module) {
  if($module == 'angularjs') {
    $libraries['angular-ui-bootstrap'] = drupal_get_library('epe_dbresource_browser','angular-ui-bootstrap');
  }
}

function epe_dbresource_browser_library() {
  $libraries['angular-ui-bootstrap'] = array(
    'title' => 'Angular UI Bootstrap',
    'website' => 'http://angular-ui.github.io/bootstrap/',
    'version' => '0.4',
    'js' => array(
      libraries_get_path('angular-ui-bootstrap') . '/ui-bootstrap-tpls-0.4.0.min.js' => array(),
    ),
    'css' => array(
      'http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css' => array(
        'type' => 'external',
      ),
    ),
  );
  return $libraries;
}
*/
